environments:
  development:
    dataSource:
      autoReconnect: true
      dbCreate: update
      username: root
      password: ""
      url: jdbc:mysql://localhost:3306/car_retailer
      driverClassName: org.mariadb.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      type: com.zaxxer.hikari.HikariDataSource
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 2000
        minIdle: 5
        maxIdle: 5
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState;StatementCache(max=200)
        defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
  test:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:ps;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      autoReconnect: true
      dbCreate: update
      username: root
      password: ""
      url: jdbc:mysql://localhost:3306/car_retailer
      driverClassName: org.mariadb.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      type: com.zaxxer.hikari.HikariDataSource
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 2000
        minIdle: 5
        maxIdle: 5
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState;StatementCache(max=200)
        defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED